Repository handshake-org/hsd, pull requests merged in 2019-04, with the labels that each got.

#121 blockchain: remove coin-cache
  etc/sample.conf
  lib/blockchain/chain.js
  lib/blockchain/chaindb.js
  lib/node/fullnode.js
Labels: stability / efficiency

#135 cli: fix typo
  bin/cli
Labels: quick

#133 mempool: remove premature witness option
  lib/mempool/mempool.js
Labels: quick

#96 bin: allow wallet to run separately from node server
  bin/spvnode
  bin/wallet
  package.json
Labels: feature, quick, ready for review, wallet

#98 txmeta: fix confirmations calculation
  lib/primitives/txmeta.js
  test/txmeta-test.js
Labels: enhancement, ready for review

#158 coinentry: remove unused parameter from JSDoc
  lib/coins/coinentry.js
Labels: docs

#161 test: contractstate
  test/contractstate-test.js
Labels: tests
