Repository handshake-org/hsd, pull requests merged in 2019-06, with the labels that each got.

#163 http: add auction endpoints
  lib/wallet/http.js
  lib/wallet/wallet.js
  test/util/common.js
  test/wallet-http-test.js
  test/wallet-http.js
Labels: api, enhancement, ready for review, wallet

#145 wallet: support alternative signers
  lib/coins/coinview.js
  lib/primitives/input.js
  lib/primitives/mtx.js
  lib/primitives/tx.js
  lib/wallet/http.js
  lib/wallet/path.js
  lib/wallet/paths.js
  lib/wallet/rpc.js
  lib/wallet/wallet.js
  lib/wallet/walletcoinview.js
  test/auction-rpc-test.js
  test/coin-test.js
  test/coins-test.js
  test/data/coin1.json
  test/data/coin1.raw
  test/data/mtx1.json
  test/data/mtx2.json
  test/data/tx1-undo.raw
  test/data/tx1.raw
  test/input-test.js
  test/mtx-test.js
  test/path-test.js
  test/util/common.js
  test/wallet-http-test.js
Labels: api, wallet

#200 jsdoc: update chain getDeployments
  lib/blockchain/chain.js
Labels: docs, quick

#190 node/http: add claims, airdrops, orphans
  lib/node/http.js
Labels: api, mempool, quick

#186 rpc and http expose identity key
  lib/net/netaddress.js
  lib/net/peer.js
  lib/node/http.js
  lib/node/rpc.js
Labels: api, p2p, ready for review
