Repository handshake-org/hsd, pull requests merged in 2019-10, with the labels that each got.

#274 dns/records: fix smime parsing bug
  lib/dns/records.js
Labels: bug, quick

#273 rpc: getnameresource return name
  lib/node/rpc.js
Labels: quick

#279 worker: use specific process title
  lib/workers/worker.js
Labels: quick, ready for review

#286 dns/record: fix ssh record object property
  lib/dns/records.js
  lib/dns/resource.js
Labels: ready for review

#281 wallet: include network in master key JSON serialization calls
  lib/wallet/masterkey.js
  lib/wallet/wallet.js
Labels: ready for review

#257 dns/server: remove duplicate opts parsing
  lib/dns/server.js
Labels: quick, ready for review

#277 test: add lib/net tests
  lib/net/packets.js
  test/net-test.js
  test/sighash-test.js
Labels: ready for review

#258 dns/server: allow configurable use of unbound
  lib/dns/server.js
  lib/node/fullnode.js
  lib/node/spvnode.js
Labels: ready for review

#259 test: rename reorg test describe blocks
  test/auction-reorg-test.js
Labels: quick, ready for review

#283 wallet: prevent chains of unconfirmed spends exceeding policy limit
  lib/wallet/txdb.js
  lib/wallet/wallet.js
  test/wallet-test.js
Labels: ready for review

#292 dns/resource: onion{ng} dnssec
  lib/dns/resource.js
Labels: ready for review
