Repository handshake-org/hsd, pull requests merged in 2020-03, with the labels that each got.

#262 Create txdb credit for known key paths when confirming
  lib/wallet/txdb.js
  test/wallet-test.js
Labels: quick, ready for review

#254 http: expose human readable service names
  lib/net/peer.js
  lib/net/pool.js
  lib/node/rpc.js
  test/node-test.js
Labels: quick, ready for review

#406 readme: update install instructions
  README.md
Labels: docs, ready for review

#201 node: event tree commit
  lib/blockchain/chain.js
  lib/node/http.js
  test/node-http-test.js
Labels: api, enhancement, ready for review

#321 node/rpc: getblock confirmation fixes
  lib/node/rpc.js
  test/node-rpc-test.js
Labels: api, quick, ready for review

#418 wallet: return wdb height in rpc getwalletinfo
  lib/wallet/rpc.js
  test/wallet-rpc-test.js
Labels: api, quick, wallet
