Repository handshake-org/hsd, pull requests merged in 2020-01, with the labels that each got.

#298 dns/server: add lookup method to rs
  lib/dns/server.js
Labels: ready for review

#94 wallet: allow duplicate open after auction expires
  lib/wallet/txdb.js
  test/wallet-auction-test.js
Labels: pre mainnet, ready for review

#322 bugfix: compute witnessRoot if a block is historical (below a checkpoint)
  lib/blockchain/chain.js
Labels: bug, quick

#331 p2p: implement two servers, plaintext + encrypted
  etc/sample.conf
  lib/net/brontide.js
  lib/net/hostlist.js
  lib/net/netaddress.js
  lib/net/peer.js
  lib/net/pool.js
  lib/node/fullnode.js
  lib/node/http.js
  lib/node/rpc.js
  lib/protocol/network.js
  lib/protocol/networks.js
  test/peering-test.js
Labels: p2p, pre mainnet, ready for review

#305 chain: disable goosig after 1 year + 1 month
  lib/blockchain/chain.js
  lib/mempool/mempool.js
  lib/node/spvnode.js
  lib/protocol/network.js
  lib/protocol/networks.js
  test/disable-goosig-test.js
Labels: pre mainnet, ready for review

#330 [consensus] No transactions for the first two weeks
  lib/blockchain/chain.js
  lib/mempool/mempool.js
  lib/protocol/network.js
  lib/protocol/networks.js
  lib/wallet/wallet.js
  test/chain-test.js
  test/mempool-test.js
  test/txstart-test.js
  test/wallet-test.js
Labels: consensus, pre mainnet

#338 pool: fix refill peers
  lib/net/pool.js
Labels: bug, pre mainnet

#339 pool: refactor fill outbound logic
  lib/net/peer.js
  lib/net/pool.js
Labels: p2p, pre mainnet, ready for review

#327 node/rpc: fix logger statement
  lib/node/rpc.js
Labels: quick, ready for review

#334 getproof - dos prevention using sliding window counter
  etc/sample.conf
  lib/net/peer.js
  lib/net/pool.js
  lib/net/slidingwindow.js
  lib/node/fullnode.js
  test/peering-test.js
  test/slidingwindow-test.js
Labels: pre mainnet

#319 Improve re-insertion of TXs from disconnected blocks into mempool
  lib/mempool/mempool.js
  test/mempool-test.js
Labels: advanced, mempool, pre mainnet, ready for review
