Repository handshake-org/hsd, pull requests merged in 2021-12, with the labels that each got.

#670 Export HTTP.TransactionOptions
  lib/wallet/http.js
Labels: quick, wallet, wallet-http, wallet-api

#556 chain: fix consensus errors and comments
  lib/blockchain/chain.js
  lib/primitives/block.js
  test/chain-test.js
  test/util/memwallet.js
Labels: enhancement, protocol/consensus, cleanup, breaking-major

#678 node-rpc: clean up hex32 method.
  lib/node/rpc.js
Labels: quick, patch
